### ISSUE TITLE
Weird Error while runing in windows vscode

### ISSUE THREAD

**Issue by anonymousRj7** [Jeomon/Web-Agent#8]
Traceback (most recent call last):
  File "C:\Users\rajsi\OneDrive\Desktop\Agents Project\Large Action Model (or Web agent)\Omniparser\OmniParser\Prasion AGent\Web-Search-Agent\app.py", line 3, in <module>
    from src.agent.web import WebSearchAgent
  File "C:\Users\rajsi\OneDrive\Desktop\Agents Project\Large Action Model (or Web agent)\Omniparser\OmniParser\Prasion AGent\Web-Search-Agent\src\agent\web\__init__.py", line 4, in <module>
    from src.agent.web.ally_tree import ally_tree_with_cordinates
  File "C:\Users\rajsi\OneDrive\Desktop\Agents Project\Large Action Model (or Web agent)\Omniparser\OmniParser\Prasion AGent\Web-Search-Agent\src\agent\web\ally_tree.py", line 118
    tree_string += f"{indent}Role: {element['role']}, Name: {element['name'].replace('\n','')}\\n"
                                                                                                  ^
SyntaxError: f-string expression part cannot include a backslash

**Comment by Jeomon** [comment]
I ran the project but I don't get this error can you use .replace('r\n','') instead
